apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kotlin
  namespace: demo-kotlin
  labels:
    app: demo-kotlin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kotlin
  template:
    metadata:
      labels:
        app: demo-kotlin
    spec:
      containers:
      - name: demo-kotlin
        image: docker.io/ghazanfar/demo-kotlin:latest
        ports:
        - containerPort: 8080
