name: 'Terraform'

on: 
  push:
    branches:
      - main
      - dev
      - stg

  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

  # defaults:
  #   run:
  #     shell: bash
  #     working-directory: terraform 

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: 'Install pre-reqs'
        run: |
          curl -SL  https://releases.hashicorp.com/terraform/1.9.3/terraform_1.9.3_linux_amd64.zip --output terraform.zip
          unzip "terraform.zip"
          mv terraform /usr/local/bin
          terraform --version
          rm terraform.zip

      - name: 'Install TFLint'
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.25.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip 
          mv tflint /usr/local/bin